# Generated by Django 5.1.3 on 2025-02-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_game_options_alter_buyer_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
    ]
